# Generated by Django 5.0.4 on 2024-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Refer ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='referredid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Referred ID'),
        ),
    ]
